### PR TITLE
Remove madness world

### PR DESCRIPTION
**Pull request by keceli**
**PR Type**

- [X] Breaking change
- [ ] Feature
- [ ] Patch

**Brief Description**

It was decided in Issue https://github.com/NWChemEx-Project/ParallelZone/issues/97 that ParallelZone no longer requires MADNESS for its functionality.
MADNESS has been used for two purposes: serialization and runtime. This PR addresses removing MADNESS world following up the earlier PR #98  on removing MADNESS archive.

**Not In Scope**

**PR Checklist**

- [ ] Documentation (comments, API, user, design, and developer as applicable)
    - [API](https://nwchemex-project.github.io/.github/documenting/writing_api_documentation.html)
    - [User](https://nwchemex-project.github.io/.github/documenting/writing_tutorials.html)
    - [Design](https://nwchemex-project.github.io/.github/documenting/writing_design_documentation.html)
    - [Developer](https://nwchemex-project.github.io/.github/documenting/writing_developer_documentation.html)
- [ ] Testing (unit, integration, performance, as applicable)
    - [Unit](https://nwchemex-project.github.io/.github/testing/unit.html)
    - [Integration](https://nwchemex-project.github.io/.github/testing/integration.html)
    - [Performance](https://nwchemex-project.github.io/.github/testing/performance.html)
- [ ] Code adheres to organization standards
    - [C++](https://nwchemex-project.github.io/.github/coding/cxx/cxx_conventions.html)
    - [Python](https://nwchemex-project.github.io/.github/coding/python/python_conventions.html)
    - [Doxygen Conventions](https://nwchemex-project.github.io/.github/documenting/doxygen_conventions.html)
    - [reST Conventions](https://nwchemex-project.github.io/.github/documenting/rst_conventions.html)

**TODOs**

- [ ] Test if it breaks other repos

### CODE REVIEW

**Comment by jwaldrop107** [comment]
If you are removing `MADworld` entirely, you can also remove the `madness` entry in `CMakeLists.txt`.

**Comment by ryanmrichard** [comment]
Given the discussion at today's meeting, let's leave MADNESS, and the initialize/finalize routines for another day. Removing MADNESS from the public API (and getting MPI info from MPI, not MADNESS) should suffice for this PR.

**Review by ryanmrichard — APPROVED** [review]

**Comment by ryanmrichard** [comment]
I guess I should have asked if we know whether or not this breaks the downstream repos?

**Comment by jwaldrop107** [comment]
Breaks `TensorWrapper`, `Integrals`, and `SCF`. They're all using the `RuntimeView::madness_world()`.

**Comment by ryanmrichard** [comment]
I assume those are easy to patch?

**Comment by jwaldrop107** [comment]
Probably the big issue is that this PR removed `madness` from everything except the `CMakeLists`, so it's not being initialized or finalized here anymore. The uses in the other repos can probably be replaced with `commpp` or get a world with the info in `commpp`.

**Comment by ryanmrichard** [comment]
Should we revert the merge?

**Comment by keceli** [comment]
Yes, this should be reverted. Our last discussion suggested still using madness for initialization. This PR disables madness initialization and finalization.

**Pull request merged**
